### PR TITLE
dev-util/electron: version bump to 1.4.15

### LINKED ISSUE #13: electron-1.4.12 is out :)
I just tried building it by simply adjusting the version number for the ebuild and the patches. The official build ships with Node 6.5.0 and they are now using `browserify` during the build process, so I simply installed the latter through npm to some directory I have in my `$PATH`, but kept Node 6.3.0, as specified via the commit hash in the ebuild. I'll see what happens once compilation is done and try it with Node 6.5.0 as well. Would it make sense to add `npm` as a build dependency and add `npm install` and adjust the `$PATH` during the (e)merge?

Anyway, it's an awesome job you've done here! I've seen the TODOs in the ebuild, maybe I'll give them a shot :)

### PR DESCRIPTION
**Pull request by ghost**
Close #13

Removed unused `readme.gentoo-r1` eclass. Probably there is more to remove.
Removed useless USE flags related to other architectures: `arm neon pic`

The `hidpi` USE flag was removed in gentoo's chromium 43

npm/nodejs is a dependency now. browserify is also necessary, so you will
probably need to install it before emerging electron: `npm install -g browserify`

The LIBCHROMIUMCONTENT_COMMIT is NOT in sync with vendor/brightray/vendor/libchromiumcontent
The working commit is `97e32dafa4a1112f14eef61a663cf39a03ed4c97` (that tip I got from Arch Linux).

### CODE REVIEW

**Comment by elprans** [comment]
> browserify is also necessary, so you will probably need to install it before emerging electron: npm install -g browserify

That's not going to fly.  We need to make this ebuild self-sufficient.  Depending on out-of-portage packages is a big no-no.  Also, we are building our own version of Node, why do we need it in the system?

**Comment by ghost** [comment]
> That's not going to fly. We need to make this ebuild self-sufficient. Depending on out-of-portage packages is a big no-no.

I see.

> Also, we are building our own version of Node, why do we need it in the system?

It's for browserify. It's used during building process. I don't know how to workaround that.

**Comment by elprans** [comment]
They seem keen to make their build process less sane with every release :-)  OK, I'll take a look.

**Comment by elprans** [comment]
I ended up wrapping ``browserify`` similarly to how I did it with ``asar``.  Merged, give it a spin.

**Pull request merged**
